### ISSUE TITLE
Javadoc, Javadoc, Javadoc

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#10]
The code is now working quite well and is pretty clean.
It is time to start adding comments!

Document all classes, members and methods using Javadoc tags.
For public methods make sure you properly explain the purpose of each parameter.

Generate the Javadoc html documentation to make sure it is properly formatted, as well as easy to read and complete.

**Comment by DrewTheRat** [comment]
This is a pre-Seneca issue, so closing it.
