### ISSUE TITLE
Implement log/trace mechanism

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#11]
In the event of a malfunction (e.g. failure to properly shoot a boulder in the high goal) during a match, it will be useful to have access to a black-box to review what happened (e.g. be able to know what the distance, alignment, and angle to target were when the shot was fired... or what buttons the pilot and co-pilot pressed) 
We therefore need some form of log/trace mechanism.

Fundamentally it might be as simple as printing a formatted output to the system console using System.out, but all entries should be time-stamped (possibly using timer on FPGA to do so)
All this should be wrapped in a class (e.g. Logger) so that it is convenient to use.

**Comment by gartaud** [comment]
Next step: test the Logger. One approach could be to log info of interest just prior to shooting the boulder (horizontal distance to goal, perceived opening width, turn angle; and tilt). Then install a ftp client on the laptop, fetch the logfile and make sure it contains what you expect.

**Comment by gartaud** [comment]
noting that Raj recommends WinSCP as the ftp client

**Comment by Endoman123** [comment]
A few questions about this while I'm working on the logger:
- Do we want a console display to show the logs we're getting realtime, then give an option to save the log?
- Do we need to save the logs onto the roboRIO? Why not just save them in a folder on the laptop?

**Comment by gartaud** [comment]
Console display would work too. Are you talking about the console display in the FRC Driver Station?

**Comment by Endoman123** [comment]
No; I made a simple Swing GUI to display the console output.

**Comment by gartaud** [comment]
Remember that the Java code is running on the robot which does not have a display. So you either need to save information on a file for later retrieval via ftp, or send information to the FRC Driver Station (to the "Messages Tab" aka DS Log Viewer it seems - which I believe support receiving user information as of this year).

**Comment by gartaud** [comment]
See http://www.chiefdelphi.com/forums/showthread.php?p=1523196

**Comment by Endoman123** [comment]
Had a feeling that that would be the case.
I don't remember if printing to the RioLog actually worked for us; I don't think we've ever tried.
Right now that isn't something I can try out, not without a robot I can deploy code to.

**Comment by gartaud** [comment]
You may assume it does and try it on the early prototype when you get a chance (next week?). It is a fairly normal process to work on software with limited access to a physical device. You write what you think should work, make sure it compiles properly... and then you test it when you get your time slice of the hardware.

**Comment by JaiPatel1** [comment]
works
