### ISSUE TITLE
Display current configuration (e.g PROTO or COMPETITION) in the Smart Dashboard

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#12]
Now that we support multiple configurations we need to make sure we pick the correct one for a given robot. We should at the minimum have a visual indicator of what configuration we are using by displaying it in the Smart Dashboard...

So add a getConfigType() method to Config so that you can get the type from the current config and put it on the smart dashboard.

**Comment by kgminer** [comment]
Done.
