### ISSUE TITLE
Attempt to fix mDNS issue(s)

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#14]
This issue created so that we have a centralized location to assess progress dealing with mDNS
1. Uninstall Bonjour (both Bonjour and Bonjour Print Services using Control Panel Uninstall or change a program) and re-enable  the NI mDNS Responder service as Bonjour did not help (by setting the service back to automatic startup and starting it or rebooting). DONE
2. Disable the Windows firewall. DONE
3. Try changing the IPv6 settings on the wireless router to  Autoconfig SLAAC/DHCPv6.
4. Try disabling IPv6 on the laptop altogether... and if this still does not work
5. add entries to host file to shortcut mDNS (file can be found under C:\Windows\System32\Drivers\etc)  (e.g. add roboRIO-1089.local 10.10.89.2, and/or roboRIO-1089-FRC.local 10.10.89.2 etc)

**Comment by gartaud** [comment]
1. Install Driver Station 16.0.2 which provides a fix for mDNS discovery (which might or might not help us)
   This can be done by installing the update suite from
   https://decibel.ni.com/content/docs/DOC-46527

**Comment by JaiPatel1** [comment]
connects without issue
