### ISSUE TITLE
Further tune the Axis camera settings to minimize the need to tune HSV filter in GRIP depending on lighting conditions

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#15]
Read suggestions for M1013 at

https://wpilib.screenstepslive.com/s/4485/m/24194/l/288984-camera-settings

(keep white balance fixed as indoor, keep backlight compensation disabled, consider decreasing exposure time further, consider decreasing brightness further, set exposure priority to motion)

**Comment by gartaud** [comment]
Also verify what the optimal focus position is. (and if infinity is good enough is it best to use it so that we can easily check that the ring is where it should be?)

**Comment by JaiPatel1** [comment]
not an issue with new LED ring
