### ISSUE TITLE
Revisit path taken when starting from P2 position in auton mode

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#19]
During the Seneca event we quickly changed the code for the P2 starting position so that we do not attempt to shoot from the side (as we got somehow uncomfortable shooting close to the target). We are now just moving forward a tiny bit and then attempting to shoot in the middle. However, P2 is too off center from the middle to make the shot, so we loose an opportunity to score points (or at least it is what it appeared it happened when we tried P2 at one time on Sunday afternoon). 
We should consider either going back to attempting to shoot on the side or we should tweak the new code so that it moves a little towards the center of the field (in front of P3) before attempting to shoot...

**Comment by DrewTheRat** [comment]
I think it is fair to close this issue. We have definitely revisited P2 and updated the autons accordingly. Re-open if you disagree...
