### ISSUE TITLE
Design the Smart Dashboard and Drive Station Controls

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2016-robot-code#2]
@gartaud - If we leave extensive control to the driver we are going a better smart display. Think about what it should contain and how the information should be presented to the driver so that he or she can act quickly without making mistake. Obvious things are if the robot is too far or too close from the target, if the robot is not sufficiently facing the target (which we could probably determine by calculating the ratio between the width and the height of the target on screen and compare it to a constant such as one), and if the robot is not pointing at the target...

**Comment by DrewTheRat** [comment]
@gartaud - 6. Think about the split between the responsibilities of the pilot/driver and the copilot/shooter. Assume that the pilot will own both joysticks and the copilot will own the Xbox controller. Which buttons should do what (you want to give to the pilot and the copilot all the buttons they need to do their job but only the buttons they need). E.g. only the pilot should be able to drive and only the copilot should be able to shoot? But who should have access to the aim/auto-rotate button? The pilot? The copilot? Both?

**Comment by DrewTheRat** [comment]
@shivamverma99 - For that we should have a discussion among ourselves and with the drive team as to what the best plan of action will be and what course of action we will take for deciding how much the driver will do and how much we will have the robot do automatically

[11:35] 
As of right now if I am not mistaken I think we were thinking about keeping one video stream but a separate message that tells the driver whether or not the robot is in range and lined up with the goal so that he can go ahead and take the shot

**Comment by gartaud** [comment]
A suggestion to discuss: add three indicators in the smart dashboard (e.g. 3 rectangles that are red or green): "distance", "clearance", and "rotation" fed by info coming from the camera.
Distance will turn green when the distance to the target is within range (i.e. robot is close enough but not too close - need to get limits from design team)
Clearance will turn green when we consider that the robot is not too much off center (i.e. width/height on camera is large enough aka perceived width is above low limit). This will probably show false-positives when we are too close to the target but should not show false-negatives
Rotation will turn green when the robot is aimed at the center of the target within a certain tolerance (which we also get from design)
We may flash "shoot" when all three indicators are green.

note: all calculations should be done in Camera.java (e.g. implement isDistanceOk(), isClearanceOk(), isRotationOk() which would all return a boolean). Then post the three values to the smart dashboard which will change the color for the indicators based on the values...

**Comment by gartaud** [comment]
we might also need a visual help to explain what button does what on the controller (for test drivers)

**Comment by gartaud** [comment]
As a side project create a "pilot handbook" explaining how to pilot the robot (what joysticks and buttons do for both pilot/driver and co-pilot/shooter; what info can be accessed in the smart display, etc).

**Comment by JaiPatel1** [comment]
display is organized
