### ISSUE TITLE
Add log entries where it would be helpful

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#20]
Seneca event showed that our logs are a little bit light when it comes to content. They are not comprehensive enough to easily diagnose issues.
We should consider adding some entries wherever we think it could be helpful to diagnose future issues (for example whenever we enter or exit a potentially problematic routine or loop).

**Comment by DrewTheRat** [comment]
@gartaud - Do you think this can be closed?

**Comment by gartaud** [comment]
I agree it can be closed
