### ISSUE TITLE
Investigate adding a chooser in the smart dashboard so that we can select the match number

### ISSUE THREAD

**Issue by gartaud** [Mercury1089/2016-robot-code#22]
It will be easier to make sure a log is for a given match if we record the match number in the log itself. This could be done easily by adding a chooser in the smart dashboard so we can select the match (e.g. Q1, QF2, etc).
Then after initializing the logger we would record the match number in the log.
If time allows look into this... Thanks.

**Comment by rpatel3001** [comment]
Might be prone to user error ie not updating the match number. The
Driverstation class exposes the alliance and driver station number that
could be used to correlate log files to match numbers.

**Comment by gartaud** [comment]
Good thinking Raj! Let's go for getTeamNumber(), getLocation(), getAlliance() and if not null value and name

**Comment by gartaud** [comment]
Getting location and alliance as Raj suggested will suffice. Closing
