### ISSUE TITLE
Code to control compressor

### ISSUE THREAD

**Issue by DrewTheRat** [Mercury1089/2016-robot-code#7]
The compressor needs to be controlled from code on the RoboRIO. This will be wired on the robot as follows:
1. Pressure switch connected to the RIO; this is a simple binary switch indicating whether we are/are not at the proper pressure.
   1. If we are not, then we need to turn on the compressor.
   2. If we are, we need to turn off the compressor
2. Spike connected to the RIO that will control a relay for compressor power; his allows us to turn the compressor on/off from code.

We will need to do the following:
1. Implement a class to encapsulate compressor control; it should:
   1. Have a method that can be called at a regular interval to check the pressure switch and turn the compressor on/off
   2. Include constants and methods to abstract the relevant sensors and controls.
2. Add code in robotInit() to create a timer to periodically check the compressor
   1. Use java.util.TimerTask to do this
   2. Interval should be fairly low - maybe 10-20ms
3. Wire components on the practice bot to simulate the compressor
   1. Simple switch to simulate the pressure switch
   2. Spike with a small motor to simulate the compressor.

**Comment by dsam7** [comment]
done, closing
