### ISSUE TITLE
random stuff

### ISSUE THREAD

**Issue by rpatel3001** [Mercury1089/2016-robot-code#8]
I had some time to look through all the code tonight, and came out with just a couple really small things I wanted to mention. I'm not sure how far along development on any of this is, I noticed that some stuff is still skeleton-y, so if there was a conscious decision behind any of these, feel free to ignore it. 

DriveTrain
1) rename lft and rft to leftControlTalon, rightControlTalon and lbt and rbt to leftFollowerTalon, rightFollowerTalon or something similar for clarity.
2) invert the necessary talon outputs and encoders instead of using constant multipliers
3) scale the joystick to the out-of-deadzone range
4) the tier system for degreeRotate looks like a great place for manual P control (not a PIDController object ie output = error \* kP) (or PI if the timeout becomes an issue)
5) why is the max turning voltage set to 6 (look into limiting the ramp rate or the current (this you'd have to do manually))

MercEncoder
1) isn't the encoder mounted on the output shaft? aka gear ratio === 1

Robot
1) consolidate brake mode settings into DriveTrain

**Comment by gartaud** [comment]
Raj. I need to digest all your comments but they all look very valid. Do you have time to come over tomorrow or Thursday to discuss them with the team? Thanks.

**Comment by gartaud** [comment]
Also can you provide your comments on the GRIP imaging chain? e.g. why do a dilate followed by an erode prior to finding the contours?  Is that based on some past experience with the 2014 robot?
(easiest way to look at it is of course to install GRIP but that just takes a few minutes...)

**Comment by rpatel3001** [comment]
The dilate-erode closes any holes that might be inside the tape target or concavities in the boundary of the contour. I'm hoping to be there Thursday, but if not, we can talk more on slack.

**Comment by DrewTheRat** [comment]
@rpatel3001 wrote:

> MercEncoder
> 1) isn't the encoder mounted on the output shaft? aka gear ratio === 1

On the practice bot this is true, but not the new robot. The output shaft drives a chain connected to the wheels. The drive sprocket is smaller than the wheel sprocket. I think we determined the ratio of drive/wheel is 3/4.

**Comment by gartaud** [comment]
Maybe "DriveShaft" would be a better name for the MercEncoder file/class (as they encompass more than the encoder)?

**Comment by DrewTheRat** [comment]
.Looking at the class, it's mostly about reading distance. I think MercEncoder is still okay for that, and we're used to the name now.

**Comment by rpatel3001** [comment]
> The output shaft drives a chain connected to the wheels

makes sense. I'll be there Thursday, hopefully at around 5:15

**Comment by gartaud** [comment]
Drivetrain items 4 and 5 (both related to turning) remain open

**Comment by gartaud** [comment]
Good enough at this point imho. I think this can be closed. Please reopen if you disagree.
